### ISSUE TITLE
Add APIs using `Result` with `thiserror` or `anyhow` crates instead of `panic`

### ISSUE THREAD

**Issue by tats-u** [PSeitz/wana_kana_rust#16]
https://github.com/search?q=repo%3APSeitz%2Fwana_kana_rust%20panic&type=code

This library can `panic` and discourages other software from adopting this library.

https://github.com/PSeitz/wana_kana_rust/issues/13

e.g. https://github.com/orgs/meilisearch/discussions/532#discussioncomment-9999921

https://docs.rs/thiserror/latest/thiserror/ and https://docs.rs/anyhow/latest/anyhow/ are widely used to handle errors without `panic`.

New APIs like `to_kana_safe()` and `to_romaji_safe()` will be appreciated.

**Comment by PSeitz** [comment]
The library should never panic. Error's don't make sense imo, since it works on a best effort basis.

 Here's how I addressed the issue:

1. Fixed the original issue 
2. Added some proptests with random and semi random input to check for panics
3. Checked the code for other potential panics

**Comment by tats-u** [comment]
Oh snap, looks like all of them are test code. Sorry to bother you.
