### ISSUE TITLE
Misleading mention of the ability to convert kanji to romaji

### ISSUE THREAD

**Issue by AlexChaplinBraz** [PSeitz/wana_kana_rust#9]
The current description reads "Utility library for checking and converting between Japanese characters - Kanji, Hiragana, Katakana - and Romaji" which isn't true.

As an example, when running `to_romaji "美味しい"` the result is `美味shii` so the kanji mention should be removed. I was looking for a library that would allow me to transform full phrases with kanji to romaji but this one doesn't do that.

It wasn't a goal for the original library anyway (https://github.com/WaniKani/WanaKana/issues/98).

**Comment by PSeitz** [comment]
True, I updated the docs. Maybe I'll add the kanji functionality in a separate crate later.

**Comment by AlexChaplinBraz** [comment]
Turns out it's actually fairly simple. Here's a modified example of the Lindera crate.

```toml
[dependencies]
lindera = "0.10"
wana_kana = "2.1"
```

```rust
use lindera::tokenizer::Tokenizer;
use wana_kana::to_romaji::to_romaji;

fn main() {
    let tokenizer = Tokenizer::new().unwrap();

    // This separates into:
    // 関西国際空港
    // 限定
    // トートバッグ
    let tokens = tokenizer.tokenize("関西国際空港限定トートバッグ").unwrap();

    for token in tokens {
        // Each token's details contains 9 "columns". Don't know what half of them are,
        // but it seems that the last two are always the reading in katakana.
        // These are the vectors of strings for the details:
        // ["名詞", "固有名詞", "組織", "*", "*", "*", "関西国際空港", "カンサイコクサイクウコウ", "カンサイコクサイクーコー"]
        // ["名詞", "サ変接続", "*", "*", "*", "*", "限定", "ゲンテイ", "ゲンテイ"]
        // ["UNK"]

        // Because it's possible that the word is unknown, use the text itself.
        let reading = if token.detail.first().unwrap() == "UNK" {
            token.text
        } else {
            // The conversion to romaji seems better with the penultimate column.
            token.detail.iter().nth(7).unwrap()
        };

        // Added a space to make it more readable.
        print!("{} ", to_romaji(reading));
    }
}

```
Which prints:
`kansaikokusaikuukou gentei tootobaggu `

This is good enough for my use case. Dunno if there's any issue with assuming that the penultimate "column" will always be the reading, but so far it was either `"UNK"` or always there. I'd like to know what this format is called, but can't find it. Everything I find assumes you already know what each column is.
